### Create profle
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE4MjI2MTYsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5MDkwMTYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.UFjFzJxKOkY2JoDwVsRc4WZh7uNNjSHIOXuzg4ft_Jkj53fVt7dJIYtrt-SyY4RrgmG37FjaKdRs7JN7Cv-R-w
Content-Type:  application/json

{
  "name": "Aaa",
  "surname": "Soliyev",
  "email": "aaa@mail.ru",
  "phone": "0000",
  "password": "1234",
  "role": "MODERATOR"
}


### update by admin
Put localhost:8080/api/v1/profile/update-by-admin?id=6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE4OTAwMTgsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5NzY0MTgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.o9vSGthi1vZwrBFfWG1a4RUWPqQbOcA0JGIaIewXg18M23XgadgOxM1L9Lw2Dd8pG2HZZNZzs7l2kdRSR8713g
Content-Type:  application/json

{
  "name": "Hello",
  "email": "hiHelloo@mail.com",
  "phone": "+998991230044",
  "password": "0102",
  "role": "PUBLISHER"
}

### update
PUT localhost:8080/api/v1/profile/update?id=6
Content-Type:  application/json

{
  "name": "Salom",
  "surname": "Salomxonov",
  "email": "Helloo@mail.com",
  "phone": "+998991230044",
  "password": "0102"
}

### Get List
GET localhost:8080/api/v1/profile/pagination?page=1&size=3

### Delete
DELETE localhost:8080/api/v1/profile/delete?id=5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE4OTAwMTgsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5NzY0MTgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.o9vSGthi1vZwrBFfWG1a4RUWPqQbOcA0JGIaIewXg18M23XgadgOxM1L9Lw2Dd8pG2HZZNZzs7l2kdRSR8713g
### Updete photo
PUT localhost:8080/api/v1/profile/update-photo?file-name
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE4OTAwMTgsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5NzY0MTgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.o9vSGthi1vZwrBFfWG1a4RUWPqQbOcA0JGIaIewXg18M23XgadgOxM1L9Lw2Dd8pG2HZZNZzs7l2kdRSR8713g
Content-Type:  application/json

### Filter
POST http://localhost:8080/api/v1/profile/filter-1
Content-Type: application/json

{
  "role": "MODERATOR"
}